package ru.fait.practicalwork;

import java.util.Arrays;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Богатырев Иван
 */
public class HrdRequestDialog extends javax.swing.JDialog {

    static Vector data1;
    static Vector data2;
    Vector newTable;
    final static String[] strColNames = {"Код сотрудника", "ФИО", "Возраст", "Пол", "Адрес", "Телефон", "Паспортные данные", "Наименование должности", "Оклад", "Обязанности", "Требования"};
    Vector<String> colNames = new Vector<String>(Arrays.asList(strColNames));

    /**
     * Creates new form requestDialog
     */
    public HrdRequestDialog(java.awt.Frame parent, boolean modal, Vector v1, Vector v2) {
        super(parent, modal);
        initComponents();
        data1 = v1;
        data2 = v2;
        newTable = new Vector();
        for (int i = 0; i < data1.size(); i++) {
            Vector temp1 = (Vector) data1.get(i);
            for (int j = 0; j < data2.size(); j++) {
                Vector temp2 = (Vector) data2.get(j);
                if (temp1.get(7).equals(temp2.get(0))) {
                    temp1.remove(7);
                    for (int k = 1; k < temp2.size(); k++) {
                        temp1.add(temp2.get(k));
                    }
                    newTable.add(temp1);
                    break;
                }
            }
        }
        DefaultTableModel tm = new DefaultTableModel(newTable, colNames);
        requestTable.setModel(tm);
        System.out.println(newTable.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        filterField = new javax.swing.JTextField();
        filterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(requestTable);

        filterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterFieldActionPerformed(evt);
            }
        });

        filterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filterLabel.setText("Должность:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterField)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(filterField))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterFieldActionPerformed
        // TODO add your handling code here:
        DefaultTableModel copy = new DefaultTableModel(colNames, 0);
        System.out.println(filterField.getText());
        if (filterField.getText().trim().replaceAll("\n", "").isEmpty()) {
            requestTable.setModel(new DefaultTableModel(newTable, colNames));
        } else {
            for (int i = 0; i < newTable.size(); i++) {
                Vector temp = (Vector) newTable.get(i);
                if (temp.get(7).toString().equalsIgnoreCase(filterField.getText())) {
                    copy.addRow(temp);
                }
            }
            requestTable.setModel(copy);
        }
        

        /*TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) requestTable.getModel())); 
        sorter.setRowFilter(RowFilter.regexFilter(filterField.getText()));

        requestTable.setRowSorter(sorter);*/
    }//GEN-LAST:event_filterFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrdRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrdRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrdRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrdRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HrdRequestDialog dialog = new HrdRequestDialog(new javax.swing.JFrame(), true, data1, data2);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filterField;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
