package ru.fait.practicalwork;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.NumberFormat;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 * @author Богатырев Иван
 */
public class MainActivity extends javax.swing.JFrame {

    final static String[] strEmpColNames = {"Код сотрудника", "ФИО", "Возраст", "Пол", "Адрес", "Телефон", "Паспортные данные", "Код должности"};
    final static String[] strPosColNames = {"Код должности", "Наименование должности", "Оклад", "Обязанности", "Требования"};
    final static String[] strGoodsColNames = {"Код товара", "Код типа", "Производитель", "Наименование", "Условия хранения", "Упаковка", "Срок годности"};
    final static String[] strTOGColNames = {"Код типа", "Наименование", "Описание", "Особенности"};
    final static String[] strSupColNames = {"Код поставщика", "Наименование", "Адрес", "Телефон", "Код поставляемого товара 1", "Код поставляемого товара2", "Код поставляемого товара 3"};
    final static String[] strCosColNames = {"Код заказчика", "Наименование", "Адрес", "Телефон", "Код потребляемого товара 1", "Код потребляемого товара2", "Код потребляемого товара 3"};
    final static String[] strStockColNames = {"Дата поступления", "Дата заказа", "Дата отпраки", "Код товара", "Код поставщика", "Код заказчика", "Способ доставки", "Объем", "Цена", "Код сотрудника"};
    Vector<String> colNames;
    Vector<String> empColNames;
    Vector<String> posColNames;
    Vector<String> goodsColNames;
    Vector<String> togColNames;
    Vector<String> supColNames;
    Vector<String> custColNames;
    Vector<String> stockColNames;

    /**
     * Creates new form MainActivity
     */
    public MainActivity() {
        initComponents();
        empColNames = new Vector<String>(Arrays.asList(strEmpColNames));
        DefaultTableModel employeesModel = new DefaultTableModel(empColNames, 0);
        employeesTable.setModel(employeesModel);

        posColNames = new Vector<String>(Arrays.asList(strPosColNames));
        DefaultTableModel positionsModel = new DefaultTableModel(posColNames, 0);
        positionsTable.setModel(positionsModel);

        goodsColNames = new Vector<String>(Arrays.asList(strGoodsColNames));
        DefaultTableModel goodsModel = new DefaultTableModel(goodsColNames, 0);
        goodsTable.setModel(goodsModel);

        togColNames = new Vector<String>(Arrays.asList(strTOGColNames));
        DefaultTableModel togModel = new DefaultTableModel(togColNames, 0);
        togTable.setModel(togModel);

        supColNames = new Vector<String>(Arrays.asList(strSupColNames));
        DefaultTableModel suppliersModel = new DefaultTableModel(supColNames, 0);
        suppliersTable.setModel(suppliersModel);

        custColNames = new Vector<String>(Arrays.asList(strCosColNames));
        DefaultTableModel costumersModel = new DefaultTableModel(custColNames, 0);
        customersTable.setModel(costumersModel);

        stockColNames = new Vector<String>(Arrays.asList(strStockColNames));
        DefaultTableModel stockModel = new DefaultTableModel(stockColNames, 0);
        stockTable.setModel(stockModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        positionsTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        goodsTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        togTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        suppliersTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        customersTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openEmployeesTableMenuItem = new javax.swing.JMenuItem();
        openPositionsMenuItem = new javax.swing.JMenuItem();
        openGoodsTableMenuItem = new javax.swing.JMenuItem();
        openTOGMenuItem = new javax.swing.JMenuItem();
        openSuppliersMenuItem = new javax.swing.JMenuItem();
        openCustomersTableItem = new javax.swing.JMenuItem();
        openStockMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        hrdMenuRequest = new javax.swing.JMenuItem();
        goodsListMenuRequest = new javax.swing.JMenuItem();
        supListMenuItem4 = new javax.swing.JMenuItem();
        custListMenuRequest = new javax.swing.JMenuItem();
        ordersMenuRequest = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Код сотрудника", "ФИО", "Возраст", "Пол", "Адрес", "Телефон", "Паспортные данные", "Код должности"
            }
        ));
        jScrollPane1.setViewportView(employeesTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Сотрудники", jPanel1);

        positionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Код должности", "Наименование должности", "Оклад", "Обязанности", "Требования"
            }
        ));
        jScrollPane2.setViewportView(positionsTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Должности", jPanel2);

        goodsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Код товара", "Код типа", "Производитель", "Наименование", "Условия хранения", "Упаковка", "Срок годности"
            }
        ));
        jScrollPane3.setViewportView(goodsTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Товары", jPanel3);

        togTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Код типа", "Наименование", "Описание", "Особенности"
            }
        ));
        jScrollPane4.setViewportView(togTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Типы товаров", jPanel4);

        suppliersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Код поставщика", "Наименование", "Адрес", "Телефон", "Код поставляемого товара 1", "Код поставляемого товара 2", "Код поставляемого товара 3"
            }
        ));
        jScrollPane5.setViewportView(suppliersTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Поставщики", jPanel5);

        customersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Код заказчика", "Наименование", "Адрес", "Телефон", "Код потребляемого товара 1", "Код потребляемого товара 2", "Код потребляемого товара 3"
            }
        ));
        jScrollPane6.setViewportView(customersTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Заказчики", jPanel6);

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Дата поступления", "Дата заказа", "Дата отпраки", "Код товара", "Код поставщика", "Код заказчика", "Способ доставки", "Объем", "Цена", "Код сотрудника"
            }
        ));
        jScrollPane7.setViewportView(stockTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        Tabs.addTab("Склад", jPanel7);

        jLabel1.setText("jLabel1");

        jMenu1.setText("Файл");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        openEmployeesTableMenuItem.setText("Открыть таблицу  сотрудников");
        openEmployeesTableMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openEmployeesTableMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openEmployeesTableMenuItem);

        openPositionsMenuItem.setText("Открыть таблицу должностей");
        openPositionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openPositionsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openPositionsMenuItem);

        openGoodsTableMenuItem.setText("Открыть таблицу товаров");
        openGoodsTableMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openGoodsTableMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openGoodsTableMenuItem);

        openTOGMenuItem.setText("Открыть таблицу типов товаров");
        openTOGMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTOGMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openTOGMenuItem);

        openSuppliersMenuItem.setText("Открыть таблицу поставщиков");
        openSuppliersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSuppliersMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openSuppliersMenuItem);

        openCustomersTableItem.setText("Открыть таблицу заказчиков");
        openCustomersTableItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCustomersTableItemActionPerformed(evt);
            }
        });
        jMenu1.add(openCustomersTableItem);

        openStockMenuItem.setText("Отркыть таблицу склада");
        openStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openStockMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openStockMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Запрос");

        hrdMenuRequest.setText("Отдел Кадров");
        hrdMenuRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrdMenuRequestActionPerformed(evt);
            }
        });
        jMenu2.add(hrdMenuRequest);

        goodsListMenuRequest.setText("Список товаров");
        goodsListMenuRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodsListMenuRequestActionPerformed(evt);
            }
        });
        jMenu2.add(goodsListMenuRequest);

        supListMenuItem4.setText("Список поставщиков");
        supListMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supListMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(supListMenuItem4);

        custListMenuRequest.setText("Список заказчиков");
        custListMenuRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custListMenuRequestActionPerformed(evt);
            }
        });
        jMenu2.add(custListMenuRequest);

        ordersMenuRequest.setText("Заказы");
        ordersMenuRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersMenuRequestActionPerformed(evt);
            }
        });
        jMenu2.add(ordersMenuRequest);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void openCustomersTableItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCustomersTableItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, custColNames.size(), custColNames, customersTable);
    }//GEN-LAST:event_openCustomersTableItemActionPerformed

    private void openEmployeesTableMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openEmployeesTableMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, empColNames.size(), empColNames, employeesTable);
    }//GEN-LAST:event_openEmployeesTableMenuItemActionPerformed

    private void openStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openStockMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, stockColNames.size(), stockColNames, stockTable);
    }//GEN-LAST:event_openStockMenuItemActionPerformed

    private void openGoodsTableMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openGoodsTableMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, goodsColNames.size(), goodsColNames, goodsTable);
    }//GEN-LAST:event_openGoodsTableMenuItemActionPerformed

    private void hrdMenuRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrdMenuRequestActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm1 = (DefaultTableModel) employeesTable.getModel();
        DefaultTableModel tm2 = (DefaultTableModel) positionsTable.getModel();
        HrdRequestDialog rd = new HrdRequestDialog(this, true, tm1.getDataVector(), tm2.getDataVector());
        rd.setVisible(true);

    }//GEN-LAST:event_hrdMenuRequestActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void openPositionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openPositionsMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, posColNames.size(), posColNames, positionsTable);
    }//GEN-LAST:event_openPositionsMenuItemActionPerformed

    private void openSuppliersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSuppliersMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, supColNames.size(), supColNames, suppliersTable);
    }//GEN-LAST:event_openSuppliersMenuItemActionPerformed

    private void openTOGMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTOGMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        class MyTxtFilter extends FileFilter {

            @Override
            public boolean accept(File file) {
                return file.isDirectory()
                        || file.getAbsolutePath().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Текстовые файлы (*.txt)";
            }
        }
        fc.setFileFilter(new MyTxtFilter());
        if (fc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File f = fc.getSelectedFile();
        fillTable(f, togColNames.size(), togColNames, togTable);
    }//GEN-LAST:event_openTOGMenuItemActionPerformed

    private void supListMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supListMenuItem4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm1 = (DefaultTableModel) suppliersTable.getModel();
        DefaultTableModel tm2 = (DefaultTableModel) goodsTable.getModel();
        SupRequestDialog rd = new SupRequestDialog(this, true, tm1.getDataVector(), tm2.getDataVector());
        rd.setVisible(true);
    }//GEN-LAST:event_supListMenuItem4ActionPerformed

    private void custListMenuRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custListMenuRequestActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm1 = (DefaultTableModel) customersTable.getModel();
        DefaultTableModel tm2 = (DefaultTableModel) goodsTable.getModel();
        CustRequestDialog rd = new CustRequestDialog(this, true, tm1.getDataVector(), tm2.getDataVector());
        rd.setVisible(true);
    }//GEN-LAST:event_custListMenuRequestActionPerformed

    private void ordersMenuRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersMenuRequestActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm1 = (DefaultTableModel) stockTable.getModel();
        DefaultTableModel tm2 = (DefaultTableModel) goodsTable.getModel();
        DefaultTableModel tm3 = (DefaultTableModel) suppliersTable.getModel();
        DefaultTableModel tm4 = (DefaultTableModel) customersTable.getModel();
        DefaultTableModel tm5 = (DefaultTableModel) employeesTable.getModel();

        OrdersRequestDialog rd = new OrdersRequestDialog(this, true, tm1.getDataVector(),
                tm2.getDataVector(), tm3.getDataVector(), tm4.getDataVector(), tm5.getDataVector());
        rd.setVisible(true);
    }//GEN-LAST:event_ordersMenuRequestActionPerformed

    private void goodsListMenuRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodsListMenuRequestActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm1 = (DefaultTableModel) goodsTable.getModel();
        DefaultTableModel tm2 = (DefaultTableModel) togTable.getModel();
        GoodsRequestDialog rd = new GoodsRequestDialog(this, true, tm1.getDataVector(), tm2.getDataVector());
        rd.setVisible(true);
    }//GEN-LAST:event_goodsListMenuRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    private void fillTable(File f, int num, Vector<String> thisColNames, javax.swing.JTable table) {
        InputStreamReader ir = null;
        BufferedReader br = null;
        try {
            ir = new InputStreamReader(new FileInputStream(f), "UTF8");
            br = new BufferedReader(ir);
            String buf;
            NumberFormat nf = NumberFormat.getNumberInstance();
            Vector data = new Vector();
            Vector row;
            while ((buf = br.readLine()) != null) {
                if (buf.equals("")) {
                    continue;
                }
                String[] sa = buf.split(";");
                row = new Vector();
                for (int i = 0; i < num; i++) {
                    row.add(sa[i]);
                }
                data.add(row);
                DefaultTableModel tm = new DefaultTableModel(data, thisColNames);
                table.setModel(tm);
            }
        } catch (IOException ex) {
            System.out.println(ex);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JMenuItem custListMenuRequest;
    public javax.swing.JTable customersTable;
    public javax.swing.JTable employeesTable;
    private javax.swing.JMenuItem goodsListMenuRequest;
    public javax.swing.JTable goodsTable;
    private javax.swing.JMenuItem hrdMenuRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JMenuItem openCustomersTableItem;
    private javax.swing.JMenuItem openEmployeesTableMenuItem;
    private javax.swing.JMenuItem openGoodsTableMenuItem;
    private javax.swing.JMenuItem openPositionsMenuItem;
    private javax.swing.JMenuItem openStockMenuItem;
    private javax.swing.JMenuItem openSuppliersMenuItem;
    private javax.swing.JMenuItem openTOGMenuItem;
    private javax.swing.JMenuItem ordersMenuRequest;
    public javax.swing.JTable positionsTable;
    public javax.swing.JTable stockTable;
    private javax.swing.JMenuItem supListMenuItem4;
    public javax.swing.JTable suppliersTable;
    public javax.swing.JTable togTable;
    // End of variables declaration//GEN-END:variables
}
